# Generated by Django 5.2 on 2025-12-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_carrito_carritoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
