# Generated by Django 5.2 on 2025-12-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Usuario', max_length=50),
            preserve_default=False,
        ),
    ]
